In [2]:
from common.util import preprocess
import numpy as np
#短いテキストを書き、それをコーパス（単語一覧）に変換する
text = "You say goodbye and I say hello."
corpus, word_to_id, id_to_word = preprocess(text)

In [3]:
from common.util import create_co_matrix
vocab_size= len(word_to_id)
#作成したコーパスから共起行列を作成する
co_matrix = create_co_matrix(corpus, vocab_size)
print(co_matrix)

[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]


In [6]:
from common.util import most_similar
query_text = "you"
most_similar(query_text, word_to_id, id_to_word, co_matrix, top=5)


[query] you
 goodbye: 0.7071067691154799
 i: 0.7071067691154799
 hello: 0.7071067691154799
 say: 0.0
 and: 0.0
